### ISSUE TITLE
OSFMount Error 'The OSFMount Driver can't be loaded'

### ISSUE THREAD

**Issue by JIMXGtamods** [ThatOSDev/UEFI-Tuts#2]
It's so annoying that when I batch mount the disk, an error appears: "The OSFMount driver cannot be loaded." so I restart the computer. When I restart the computer it works but when I do it too many times the error occurs, same thing when reinstalling. So now I want another mount exe because of this or a fix. I'm on Windows 11.

**Comment by ThatOSDev** [comment]
Sorry it took so long. If you watched my latest youtube videos, you would have seen that I am homeless, meaning I also have no internet.

As for OSFMount, I had the same problem on windows 10 as you do. However, I was able to solve it.

It turns out it was a windows code signing problem. Here is the link that I had read and used in order to attempt a fix.

https://www.osforensics.com/faqs-and-tutorials/error_loading_osfmount_driver.html

https://en.wikipedia.org/wiki/Code_signing

Interestingly enough, I had to fix my clock. The time on my computer was somehow wrong. I updated it, and suddenly OSFMount installed, but only AFTER I uninstalled the previous install.

I hope this helps. PLEASE write back if you are still unable to get it fixed, and I will see if I can retrace my steps on how I fixed it on my end.

SIDE NOTE : I had never ran into this before, except that one time. Seems that windows updates somehow fixed it.

**Comment by JIMXGtamods** [comment]
Sorry for your difficult situation :( , may god help you. Sorry for my late late late responce. But thanks you for replying!! So i retest it out without any changes, no work. BUT when i fix the clock, ITS WORKING!!!!!! Thanks you!!

**Comment by ThatOSDev** [comment]
> Sorry for your difficult situation :( , may god help you. Sorry for my late late late responce. But thanks you for replying!! So i retest it out without any changes, no work. BUT when i fix the clock, ITS WORKING!!!!!! Thanks you!!


Yea I noticed the clock affects a lot of software. Glad it's an easy fix.

As for being homeless, I'm working on that. Finally get my truck in a week. That's step 1 to getting off the streets. Once I am stable, I hope to write more code and youtube videos.

Cheers
